// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Monster/MonsterState.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common.Proto.Monster {

  /// <summary>Holder for reflection information generated from Monster/MonsterState.proto</summary>
  public static partial class MonsterStateReflection {

    #region Descriptor
    /// <summary>File descriptor for Monster/MonsterState.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MonsterStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpNb25zdGVyL01vbnN0ZXJTdGF0ZS5wcm90bxIUQ29tbW9uLlByb3RvLk1v",
            "bnN0ZXIqLgoMTW9uc3RlclN0YXRlEggKBElETEUQABIICgRNT1ZFEAESCgoG",
            "QVRUQUNLEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Common.Proto.Monster.MonsterState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MonsterState {
    [pbr::OriginalName("IDLE")] Idle = 0,
    [pbr::OriginalName("MOVE")] Move = 1,
    [pbr::OriginalName("ATTACK")] Attack = 2,
  }

  #endregion

}

#endregion Designer generated code
