// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Base/NetError.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MMORPG.Common.Proto.Base {

  /// <summary>Holder for reflection information generated from Base/NetError.proto</summary>
  public static partial class NetErrorReflection {

    #region Descriptor
    /// <summary>File descriptor for Base/NetError.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetErrorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNCYXNlL05ldEVycm9yLnByb3RvEhhNTU9SUEcuQ29tbW9uLlByb3RvLkJh",
            "c2UqsAIKCE5ldEVycm9yEgsKB1N1Y2Nlc3MQABIQCgtVbmtub3dFcnJvchDp",
            "BxIPCgpPdXRPZlJhbmdlEOoHEhIKDUxvZ2luQ29uZmxpY3QQ0Q8SIAobSW5j",
            "b3JyZWN0VXNlcm5hbWVPclBhc3N3b3JkENIPEhQKD0lsbGVnYWxVc2VybmFt",
            "ZRC5FxIZChRJbGxlZ2FsQ2hhcmFjdGVyTmFtZRC6FxIiCh1DaGFyYWN0ZXJD",
            "cmVhdGlvbkxpbWl0UmVhY2hlZBC7FxIVChBJbnZhbGlkQ2hhcmFjdGVyELwX",
            "EhMKDlJlcGVhdFVzZXJuYW1lEKEfEhgKE1JlcGVhdENoYXJhY3Rlck5hbWUQ",
            "oh8SEgoNSW52YWxpZEVudGl0eRCJJxIPCgpJbnZhbGlkTWFwEIonYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MMORPG.Common.Proto.Base.NetError), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum NetError {
    [pbr::OriginalName("Success")] Success = 0,
    [pbr::OriginalName("UnknowError")] UnknowError = 1001,
    [pbr::OriginalName("OutOfRange")] OutOfRange = 1002,
    [pbr::OriginalName("LoginConflict")] LoginConflict = 2001,
    [pbr::OriginalName("IncorrectUsernameOrPassword")] IncorrectUsernameOrPassword = 2002,
    [pbr::OriginalName("IllegalUsername")] IllegalUsername = 3001,
    [pbr::OriginalName("IllegalCharacterName")] IllegalCharacterName = 3002,
    [pbr::OriginalName("CharacterCreationLimitReached")] CharacterCreationLimitReached = 3003,
    [pbr::OriginalName("InvalidCharacter")] InvalidCharacter = 3004,
    [pbr::OriginalName("RepeatUsername")] RepeatUsername = 4001,
    [pbr::OriginalName("RepeatCharacterName")] RepeatCharacterName = 4002,
    [pbr::OriginalName("InvalidEntity")] InvalidEntity = 5001,
    [pbr::OriginalName("InvalidMap")] InvalidMap = 5002,
  }

  #endregion

}

#endregion Designer generated code
